# Testing workflow: If scratch.txt has `fail` in it, fails
name: Choose to Fail
on:
  pull_request:
jobs:
  choose_to_fail:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: "! grep fail scratch.txt"
