name: Matrix Test
on:
  pull_request:
jobs:
  # choose_to_fail_matrix:
  #   strategy:
  #     matrix:
  #       phrase: ["matrix1", "matrix2"]
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3
  #   - run: "! grep ${{ matrix.phrase }} scratch.txt"
  choose_to_fail_matrix:
    strategy:
      matrix:
        attempt: [2]
    runs-on: ubuntu-latest
    steps:
      - run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
