name: Workflow Run Test
on:
  workflow_run:
    workflows: [Matrix Test]
    types:
    - completed
jobs:
  workflow_run_test:
    runs-on: ubuntu-latest
    steps:
    - run: echo $JSON
    env:
      JSON: ${{ toJSON(github) }}
